export type {
  DecodedIdToken,
  UserRecord,
  UserIdentifier,
  GetUsersResult,
  ListUsersResult,
  CreateRequest,
  UpdateRequest,
  DeleteUsersResult,
  SessionCookieOptions,
  AuthProviderConfig,
  UpdateAuthProviderRequest,
  AuthProviderConfigFilter,
  ListProviderConfigResults,
  ActionCodeSettings,
  UserImportRecord,
  UserImportOptions,
  UserImportResult,
  HashAlgorithmType,
  UserMetadataRequest,
  UserProviderRequest,
  SAMLAuthProviderConfig,
  OIDCAuthProviderConfig,
  SAMLUpdateAuthProviderRequest,
  OIDCUpdateAuthProviderRequest,
  MultiFactorCreateSettings,
  MultiFactorUpdateSettings,
  MultiFactorSettings,
  UserMetadata,
  UserInfo,
  UserProvider,
  FirebaseArrayIndexError,
  FirebaseError,
  UidIdentifier,
  EmailIdentifier,
  PhoneIdentifier,
  ProviderIdentifier,
  CreatePhoneMultiFactorInfoRequest,
  UpdatePhoneMultiFactorInfoRequest,
  OAuthResponseType,
  MultiFactorInfo,
} from "./types/firebase-admin/index.js";

export type { ServiceAccountKey } from "./types/service-account-key.js";
export type { SetAccountInfoResponse, ProviderUserInfo } from "./types/google-auth.js";
